pool:
  vmImage: ubuntu-16.04

variables:
  SOURCE_PATH: $(Build.SourcesDirectory)/html
  CONNECTION_STRING: $(ConnectionString)

steps:
- script: echo hello world
- script: |
    az extension add --name storage-preview
    az storage blob upload-batch -s $SOURCE_PATH -d '$web' --connection-string "$CONNECTION_STRING"
