pool:
  vmImage: ubuntu-16.04

steps:
- script: |
    if [ -z "$AZURE_STORAGE_CONNECTION_STRING" ]; then
      echo "!! Empty AZURE_STORAGE_CONNECTION_STRING"
    fi
    az extension add --name storage-preview
    az storage blob upload-batch -s $SOURCE_PATH -d '$web'
  displayName: Upload those blobs
  env:
    SOURCE_PATH: $(Build.SourcesDirectory)/html
    AZURE_STORAGE_CONNECTION_STRING: $(CONNECTION_STRING)
